#!/bin/bash

tailscale status >/dev/null || exit 0

LABEL=${LABEL:-'ts:'}

ip=$(tailscale ip | head -n1)
machine_name=$(tailscale whois $ip | grep -oP -m1 'Name: +\K[^\.]+')

msg+="$LABEL $machine_name"
exit_node=$(tailscale exit-node list | awk '/selected/ {print $2}' | cut -d. -f1)
[[ -n $exit_node ]] && msg+=" (exit: $exit_node)"

echo $msg

